### ISSUE TITLE
Python Dev Container?

### ISSUE THREAD

**Issue by Antebios** [qdm12/reactdevcontainer#19]
Have you thought about creating a Python Dev Container?  If not, why not?  Or does Anaconda takes care of this?  I find that Anaconda doesn't play nice with other python stuff, but I deal with it.

**Comment by qdm12** [comment]
Hi there!

I don't because I don't use Python (anymore, for years now);
Even on languages I use from time to time such as Rust or React, I have dev containers published but I wish I wouldn't since I don't fully maintain them since I am not aware of all the latest features/releases and so on. If you want however, feel free to fork or copy/pasta this repository and use the infrastructure in place to maintain a python dev container 😉 

On the other hand, there are some that already exist, check out https://github.com/microsoft/vscode-remote-try-python 😉
